services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway:/app
    depends_on:
      - user-service
      - cart-service
      - order-service
      - payment-service
      - notification-service

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "5001:5000" # host:container
    env_file:
      - ./services/user-service/.env
    volumes:
      - ./services/user-service:/app
    depends_on:
      - user-db

  cart-service:
    build: ./services/cart-service
    container_name: cart-service
    ports:
      - "5002:5000"
    env_file:
      - ./services/cart-service/.env
    volumes:
      - ./services/cart-service:/app
    depends_on:
      - cart-db

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "5003:5000"
    env_file:
      - ./services/order-service/.env
    volumes:
      - ./services/order-service:/app
    depends_on:
      - order-db
      # - payment-service
      # - notification-service

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "5004:5000"
    env_file:
      - ./services/payment-service/.env
    volumes:
      - ./services/payment-service:/app
    depends_on:
      - payment-db

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "5005:5000"
    env_file:
      - ./services/notification-service/.env
    volumes:
      - ./services/notification-service:/app
    depends_on:
      - redis

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "5006:5000"
    env_file:
      - ./services/product-service/.env
    volumes:
      - ./services/product-service:/app
    depends_on:
      - product-db

  # Databases for each service (isolated per service)

  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    ports:
      - "5440:5432"
    volumes:
      - ./postgres/user-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users

  cart-db:
    image: postgres:15
    container_name: cart-db
    restart: always
    ports:
      - "5441:5432"
    volumes:
      - ./postgres/cart-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carts

  order-db:
    image: postgres:15
    container_name: order-db
    restart: always
    ports:
      - "5442:5432"
    volumes:
      - ./postgres/order-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders

  payment-db:
    image: postgres:15
    container_name: payment-db
    restart: always
    ports:
      - "5443:5432"
    volumes:
      - ./postgres/payment-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments

  product-db:
    image: postgres:15
    container_name: product-db
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - ./postgres/product-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6381:6379"
